/// Flutter icons CoreIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CoreIcons
///      fonts:
///       - asset: fonts/CoreIcons.ttf
///
///
///
// ignore_for_file: public_member_api_docs

library;

import 'package:flutter/widgets.dart';

class CoreIcons {
  CoreIcons._();

  static const _kFontFam = 'CoreIcons';
  static const String _kFontPkg = 'core';

  static const IconData company =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData asset =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData component =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
